# Generated by Django 4.2.3 on 2023-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gelenarama',
            name='tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
