# Generated by Django 4.2.3 on 2023-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehberapp', '0002_kisi_slug_alter_gelenarama_tel_alter_kisi_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
