# Generated by Django 4.2.3 on 2023-07-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rehberapp', '0003_sirket_slug_alter_kisi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='sirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehberapp.sirket'),
        ),
    ]
